### ISSUE TITLE
Stop spamming

### ISSUE THREAD

**Issue by AlexJakeGreen** [binary-com/mobile#356]
Please tell Martina Fong that it is not polite to send spam and use bots.

**Comment by AlexJakeGreen** [comment]
Неre's the spam send by your employee

I found your details on LinkedIn whilst searching for DevOps / Perl / Front-end / Software Test / Information Security / DBA experts. Following my review, I believe that you might be a good fit for a career opportunity with our company.

Binary.com is an international binary options trading company with offices in Malaysia, Malta and Japan. Cyberjaya, Malaysia is the center for our global IT operations group which is staffed by talented IT professionals drawn from technical centers around the world. 

Our company pays special attention to professional recruitment, so as to ensure that we engage only the most talented developers and engineers. Each candidate for employment is assessed using a difficult technical exercise that ensures we onboard engineers offering both extensive experience and a strong interest in the field. Our recruitment tests are also designed to select IT professionals with character traits that include sound judgment, teamwork, a strong work ethic, motivation and a commitment to excellence in software development and development operations.

At Binary.com, we offer our IT staff the best possible working conditions to help them advance in their careers. This means flexible working hours, a casual dress code, and the best equipment available. We provide each of our engineers with a high-end MacBook laptop, and use only the newest and best equipment in our production server environment. We customised a purpose-built office, designed to provide our engineers with a comfortable and productive work space.

We believe in developing a company culture based on trust and camaraderie, a flat hierarchy, open and transparent communication, integrity and honesty, an entrepreneurial and fast-moving pace, and providing our employees with the best possible environment and tools that the company can provide.

We are a very successful company with global reach, founded in 1999, and growing rapidly. Whereas in 2010 our website supported on average 15,000 options transactions per day, today we routinely transact in over 1,000,000 per day – a 66-fold increase in just 5 years. Working in a fast-growing organization requires us to develop robust systems, coupled with a high-quality and well-architectured code, and a strong focus on security.

Our back-end technologies include Linux, Perl, Postgres, Redis, Chef, nginx, and cloud providers such as AWS. We are presently implementing a high-performance Websockets-based API and intend to re-write our website’s front-end using latest Javascript-based frameworks.

Our software development philosophy is based on the git forking model and a vigorous process of code review to ensure only high quality code makes it into our codebase, good test coverage, prioritizing refactoring of code to pay back technical debt, attention to code architecture, simplicity and readability, rapid releases (we release code every day), outsourcing of non-core functions to cloud providers, and the adoption of latest technologies whenever possible. We aim to comply with all 12 points of the Joel Test.

We provide our staff with an impressive array of rewards that include competitive remuneration packages and employee benefits such as health insurance, a generous annual bonus program for top performers, exciting company trips around Asia, and the opportunity to participate in a meritocracy where talented professionals can assume positions of increasing responsibility.

We are a highly international organisation, with staff from over 15 different countries. A large percentage of our employees in Malaysia are expats, from all over the world. We make relocation simple, arranging work permits and dependent passes for spouses and children, flights, initial accommodation in Cyberjaya, and other required assistance for overseas candidates.

If you would like to learn more about our company, we invite you to visit www.binary.com/careers, http://blog.wobb.my/project/binary/, and to read about our history at www.binary.com/group-history. Our open-source contributions may be found at https://github.com/binary-com. To support the rapid growth of our website’s business we are recruiting in all our IT departments – front-end development (Javascript & CSS-based technologies and frameworks), back-end development (Perl), DevOps (Chef), and Quantitative Analysis (financial mathematics, mainly Python, R, Matlab) – and both for junior and senior positions.

Should you be interested in applying for one of our open positions, we invite you to forward your current CV. We’ll respond promptly with a recruitment testing package to help us determine whether there’s a technical and cultural fit within our organization.

I look forward to hearing from you.

Best regards,
Martina Fong

**Comment by ashkanx** [comment]
Hi Alex, How many times have you received this email?

**Comment by AlexJakeGreen** [comment]
Hi. The e-mail was sent to account which starts with words "for.spam....". Those who sends to for.spam@ already agreed they're sending spam.

**Comment by ashkanx** [comment]
Alex;
We never intend to [spam](https://en.wikipedia.org/wiki/Spamming) anyone. In fact [Spamming definition ](https://en.wikipedia.org/wiki/Spamming)is totally different from what we do :)
Anyway, We will remove you from the list.

Thanks

**Comment by AlexJakeGreen** [comment]
thanks :)
